/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DatetimeSlotPicker {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDatetimeSlotPickerElement extends Components.DatetimeSlotPicker, HTMLStencilElement {
    }
    var HTMLDatetimeSlotPickerElement: {
        prototype: HTMLDatetimeSlotPickerElement;
        new (): HTMLDatetimeSlotPickerElement;
    };
    interface HTMLElementTagNameMap {
        "datetime-slot-picker": HTMLDatetimeSlotPickerElement;
    }
}
declare namespace LocalJSX {
    interface DatetimeSlotPicker {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "datetime-slot-picker": DatetimeSlotPicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "datetime-slot-picker": LocalJSX.DatetimeSlotPicker & JSXBase.HTMLAttributes<HTMLDatetimeSlotPickerElement>;
        }
    }
}
